'\" t
.\"     Title: stdlib
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-07-02
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "STDLIB" "1" "2025-07-02" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
stdlib \- blah
.SH "SYNOPSIS"
.sp
stdlib <command> [flags]
.SH "DESCRIPTION"
.sp
Bunch of random functions that make working in bash more fun
.SH "FUNCTIONS"
.sp
stdlib\-url\-join(1)
.RS 4
One or more path components to join together
.RE
.sp
stdlib\-url\-parse(1)
.RS 4
The URL to parse (required)
.RE
.SH "EXAMPLES"
.sp
.if n .RS 4
.nf
.fam C
$ stdlib url/join "api" "v1" "users"
api/v1/users
.fam
.fi
.if n .RE